import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "WORKOUT",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="flex px-48 justify-between h-14 align-middle mb-8 items-center">
            <h3 className="font-semibold">WORKOUT</h3>
            <ul className="flex justify-between gap-8">
              <li className="text-white/70">EXERCISES</li>
              <li className="text-white/70">TRAINERS</li>
              <li className="text-white/70">PRICING</li>
              <li className="text-white/70">LOGIN</li>
            </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
